name: GraphQL Validation
on: push
jobs:
  graphql-validate:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.x
      - name: install deps
        run: yarn install
      - name: run codegen
        run: yarn run generate
